
title: Articulos
name: Articulos
description: site personal de Miguel Granadino
timezone: Europe/Madrid
site_url: https://akira3030.github.io/formacion



markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'




plugins:
 - jemoji


