
# Inicio
title: Articulos
name: Articulos
description: site personal de Miguel Granadino
timezone: Europe/Madrid

lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouger


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji


