
# Inicio
title: Articulos
name: Articulos
description: site personal de Miguel Granadino
timezone: Europe/Madrid

# Site Author


# Reading Files

# Conversion

# Markdown Processing

# Collections

# Defaults

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji


